### PR TITLE
Update lock params

### PR DESCRIPTION
**Pull request by lunaru**
@pat The sidekiq params need an update to work with newer versions of sidekiq.

### CODE REVIEW

**Comment by pat** [comment]
Thanks for the fix @lunaru - I'm just wondering if there's a way we can support old _and_ new syntax? Is it possible to detect the version of Sidekiq and then send through the appropriate settings?

**Comment by lunaru** [comment]
@pat It would be a bit ugly to have the `lock` vs `unique` check in the code itself, but here's a thought: It looks like `unique` was changed to `lock` in `sidekiq-unique-jobs` after version 6.x (btw, `sidekiq-unique-jobs` is actually an implicit requirement of this gem!). What do you think about adding this as a requirement in the gemspec and bumping the major version number as part of this PR?

That way ts-sidekiq-delta can move forward with healthy code with a dependency split by major version increment, which is standard practice in open source anyway.

**Comment by lunaru** [comment]
@pat I've updated this PR based on my proposed solution for this so that users of this gem can select the right version for them based on gem versioning, which is standard practice.

Let me know what you think.

**Comment by lunaru** [comment]
@pat pinging again to see if we can get this going

**Comment by pat** [comment]
Thanks @lunaru - I hadn't forgotten, but probably won't have time today. Hopefully later this week I'll get this merged in and a new gem released. 🤞

**Comment by pat** [comment]
Just pushed 0.3.0 :) Thanks for the patch!

**Pull request merged**
